platform :ios, '8.0'

use_frameworks!
inhibit_all_warnings!

target "ImagePickerDemo" do
  pod 'ImagePicker', path: '../../'
  pod 'MainThreadGuard', :git => 'https://github.com/onmyway133/MainThreadGuard'
end
